name: QA Tests On Demand (By Tag)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Ingresa el TAG para ejecutar (ej: @login, @register_product, @update_product_invalid)'
        required: true
        default: '@login'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests with Tag Filter
        run: mvn clean test -Dkarate.tags="${{ inputs.tag }}"

      - name: Publish Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: karate-reports-${{ inputs.tag }}
          path: target/karate-reports